server:
  port: 9017
  servlet:
    #    设置响应的字符编码
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: langchain4j-17chat-rag-advanced
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/ai-memory?authSource=admin


